import Head from 'next/head'
import styles from '../styles/Home.module.css'
import db from '../backend/db';
// import productModel from '../backend/DBModels/productModel';


import getConfig from "next/config";
const { publicRuntimeConfig } = getConfig();

//  const NEXT_PUBLIC_DATABASE_CONNECTION= publicRuntimeConfig.NEXT_PUBLIC_DATABASE_CONNECTION


export default function Home({ topRatedProducts, theEnvSecret }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 >
          the env secret is 1 + 1 = :
          {theEnvSecret ? theEnvSecret : ":::no value "}
        </h1>

        <h3>
          {
           JSON.stringify( topRatedProducts)
          }
        </h3>

      </main>

     
    </div>
  )
}

export async function getStaticProps() {

  const conn = await db.connect(process?.env?.DATABASE_CONNECTION);
  // const
  //   topRatedProducts = await productModel.find({}, '-reviews')
  //     .lean()
  //     .sort({ rating: -1 })
  //     .limit(4)

  db.disconnect();

  return {
    props:
    {
       topRatedProducts: {"a": String(process?.env?.DATABASE_CONNECTION?.slice(0, 8))  },
      //  topRatedProducts: topRatedProducts.map(db.cocStringify),
       
      //  theEnvSecret: process.env.xxx || 
      theEnvSecret: conn ||
      // theEnvSecret: process.env.xxx ||


        //  process.env.NEXT_PUBLIC_xxx  || 
        // publicRuntimeConfig.xxx ||
        // publicRuntimeConfig.NEXT_PUBLIC_xxx ||

        new Date().toTimeString().slice(0, 8)
    }
  }
}
